config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "pages#index"
  
  get "posts" => "post#index"
  get "posts/new" => "post#new"
  post "posts" => "post#create"
  get "posts/:id" => "post#show", as: "post"
  get "posts/:id/edit" => "post#edit", as: "post_edit"
  patch "posts/:id" => "post#update"
  delete "posts/:id" => "post#destroy"

  post "post/:id/comments" => "comment#create", as: "post_comments"
  delete "post/:id/comments/" => "comment#destroy"

  get "users/:id" => "pages#user", as: "user"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :post
	belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
	validates :title, :text, :code, presence: true
	belongs_to :user
	has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :posts
  has_many :comments
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception


  helper_method :current_user

 
end

app/controllers/comment_controller.rb
class CommentController < ApplicationController

def create
	@post = Post.find(params[:id])
	comment =  current_user.comments.build(comment_params)

	if comment.save
		redirect_to post_path(@post)
	else
		flash[:errors] = comment.errors.full_messages
		redirect_to post_path(@post)
	end
	
end

def destroy
	comment = Comment.find(params[:id])
	post_id = comment.post_id
	comment.destroy
	redirect_to post_path(post_id)
end

private

def comment_params
	params.require(:comment).permit(:comment_text, :post_id)
end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def index
	end

	def user 
		@user = User.find(params[:id])
		@user_posts = @user.posts.limit(2)
	end
end

app/controllers/post_controller.rb
class PostController < ApplicationController
	def index
		@posts = Post.all
	end

	def new
		@post = Post.new
	end

	def create
		post = current_user.posts.build(post_params)

		if post.save
			redirect_to :root
		else
			flash[:errors] = post.errors.full_messages
			redirect_to :posts_new
		end
	end

	def show
		@post = Post.find(params[:id])
		@comments = Comment.where(post_id: @post.id)
	end

	def edit
		@post = Post.find(params[:id])
	end

	def update
		post = Post.find(params[:id])

		if post.update(post_params)
			redirect_to post_path(post.id)
		else
			flash[:errors] = post.errors.full_messages
			redirect_to post_edit_path(post.id)
		end
	end

	def destroy
		post = Post.find(params[:id])
		post.destroy
		redirect_to :root
	end
	
	private

	def post_params
		params.require(:post).permit(:title, :text, :code)
	end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:nickname, :rating, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:nickname, :bio, :email, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> ScreenCode<%= yield(:title) %></title>
    <%= csrf_meta_tags %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script> 
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </head>
<header>
    <ul>
        <li><%= link_to "ScreenCode", root_path %> </li>
        <li class="auth">
        <span><a href="#"> Log in </a></span>
        <span><a href="#"> Sign up </a></span>
        </li>
    </ul>
</header>

  <body>
    <%= yield %>
    
  </body>

  <footer >
    <p> ScreenCode organization 2017</p>
  </footer>
</html>

app/views/pages/index.html.erb
<div class="banner">
		<div class = "leftHalf">
			<p><em>ScreenCode is a <strong>social problem solving environment</strong> for coders.</em></p>
			<span>You can fix your problem with errors in code or get good experience with nice code editing, post your screen and you are welcome in our amiable society.</span>
		</div>
		<div class = "rightHalf">
			<%= image_tag "3.jpg"%>
		</div>
	</div>

app/views/pages/user.html.erb
<div class="container">		
	<div class="leftPanelOfScreen">
		<div class=fakeMenu>
		<div class="fakeButtons fakeClose"></div>
		<div class="fakeButtons fakeMinimize"></div>
		<div class="fakeButtons fakeZoom"></div>
		<div class="screenName"></div>
		</div>
		<div class="fakeScreen">
		.fakeButtons 
		</div>
	</div>

	<div class="rightPanelOfScreen">
		<div class=fakeMenu>
		<div class="fakeButtons fakeClose"></div>
		<div class="fakeButtons fakeMinimize"></div>
		<div class="fakeButtons fakeZoom"></div>
		<div class="screenName"></div>
		</div>
		<div class="fakeScreen">
		test
		</div>
	</div>


<div class="userBio">
<ul>
	<li><%= image_tag "1.jpg", class: "imgProfile"%></li>
	<li><h2><%= @user.nickname %></h2>	</li>				
</ul>	
<h4>
<span><i style="font-size:18px" class="fa">&#xf073;</i></span> Member since <%= @user.created_at.to_formatted_s(:day_month_and_year) %></h4>
<h4><span><i class="fa fa-line-chart" style="font-size:18px"></i></span>  Rating: <%= @user.rating %> </h4>

<h4>Highlights:</h4>
<p><%= @user.bio %> </p>
</div>
</div>

app/views/post/_form.html.erb
<% if flash[:errors] %>
	<% flash[:errors].each do |e| %>
	<p><%= e %></p>
	<% end %>
<% end %>

<%= form_for(@post)  do |f| %>
<div>
	<%= f.label :title %>
	<%= f.text_field :title %>
</div>
<div>
	<%= f.label :text, "Description" %>
	<%= f.text_field :text %>
</div>

<div>
	<%= f.label :code %>
	<%= f.text_area :code %>
</div>
<%= f.submit "Screen" %>
<% end %>

app/views/post/edit.html.erb
<% content_for(:title, " Edit #{@post.title}") %>
<%= render partial: "post/form" %>

app/views/post/index.html.erb
<% content_for(:title, " Gallery") %>
<div class = "container">
<h1>Welcome to ScreenCode Project. Here you can explore Screens from other users.</h1>	
<div class="wrapper">
<% @posts.each do |p| %>
<div class="post">
	<h2><%=link_to p.title, post_path(p.id) %></h2>
	<p class="textOfPost"><%= p.text %></p>
	<div class="settings">
	<span><%= link_to "Edit", post_edit_path(p.id) %></span> 
	<span><%= link_to "Delete", post_path(p.id) , data={method: :delete} %></span> 
	</div>
</div>
<% end %>
</div>
<h3>Totaly <%= @posts.count %> screencodes.</h3>
<p id=welcome>You can fix your problem with errors in code or get good experience with nice code editing, just <a href="/posts/new"><b> post your screen </b></a> and you are welcome in our amiable society.</p>
</div>

app/views/post/new.html.erb
<% content_for(:title, " Screen your Code") %>
<%= render partial: "post/form" %>

app/views/post/show.html.erb
<% content_for(:title, " #{@post.title}") %>
<h1 >Screencode</h1>

<div class="showPosts">
	
<h2><%= @post.title %></h2>
<p><%= @post.text %></p>


<div class=fakeMenu>
  <div class="fakeButtons fakeClose"></div>
  <div class="fakeButtons fakeMinimize"></div>
  <div class="fakeButtons fakeZoom"></div>
  <div class="screenName"><%= @post.title.downcase %></div>
</div>
<div class="fakeScreen">
<%= @post.code %>
</div>

</div>
<div class="containerOfComments">
<% @comments.each do |c| %>

<div class="commentField">
<ul>
  <li><img src="http://gzsihai.com/data/out/43/im-500200020.png" alt="commentUserPhoto"></li>
  <li>Anonymus</li>
  <li><%= c.comment_text %></li>
  <li><%= link_to "Delete", post_comments_path(c.id) , data={method: :delete} %></li>
</ul>
</div>
<p></p>
<% end %>
</div>
<%= form_for([@post, @post.comments.build]) do |f| %>
  <div class="field">
    <%= f.label :comment_text %><br />
    <%= f.text_area :comment_text, placeholder: "Write your comment ...", cols: "80", class: 'formTextarea' %>

  </div>
  <%= f.hidden_field :post_id %>
  <div class="actions">
    <%= f.submit %> 
  </div>
<% end %>	